DefaultContentLanguage = "en"
author = "LZX"
baseURL = "https://m00nwandering.life/"
copyright = "Copyright © 2019–2024"
disqusShortname = "LZX"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
googleAnalytics = "UA-FAKE" ## or "G-xxxxxxxx" in Google Analytics v4, in hugo v0.82+
hasCJKLanguage = true
languageCode = "cn"
theme = "hugo-theme-tokiwa"
title = "清夜无尘の一方天地"

[markup]
[markup.highlight]
style = "monokailight"

[markup.goldmark.renderer]
unsafe = true

[params]
bannerFont = "fonts/exampleFont" 
description = """
清夜无尘，月色如银。酒斟时、须满十分。浮名浮利，虚苦劳神。叹隙中驹，石中火，梦中身。
虽抱文章，开口谁亲。且陶陶、乐尽天真。几时归去，作个闲人。对一张琴，一壶酒，一溪云。
""" 
env = "production" # for Google Analytics and DISQUS.
favicon = "img/favicon-32x32.png" 
fuse = true # for searchbox. "JSON" must added to output contents. See [outputs].
math = true # for introducing $KaTeX$
useChineseFonts = true 
postDateFormat = "2006-1-2"

[menu]
# Shown in the side menu.
[[menu.main]]
identifier = "post"
name = "Post"
url = "/post/"
weight = 1
[[menu.main]]
name = "Tags"
url = "/tags/"
weight = 2

[[menu.main]]
name = "Categories"
url = "/categories/"
weight = 2

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 3

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
[social]
bilibili = "https://bilibili.com/"
github = "https://github.com/"
gitlab = "https://gitlab.com/"
instagram = "https://instagram.com/"
mail = "https://mail.google.com"
twitter = "https://twitter.com/"
weibo = "https://weibo.com/"
youtube = "https://youtube.com/"
zhihu = "https://zhihu.com/"
# any icon in layouts/partials/svg can be used by the name without the "-line.svg"

[outputs]
home = ["HTML", "RSS", "JSON"]

[module]
[[module.imports]]
  path = "github.com/heyeshuang/hugo-theme-tokiwa"